增加do while语句和switch语句，修复了数组的一些小问题
Planecode/SimpleComplier pull request #75
Opened 2019-12-08 06:22 UTC by ADANIE

2019-12-08 06:54 UTC, Plane-walker commented on analysis/list.h
> +            control_jump->jump_true(label);
这里为真直接跳回去，不需要跳到无条件跳转再跳回去

2019-12-08 06:54 UTC, Plane-walker commented on analysis/list.h
> +        node *case_list = nowNode->cNode[1]->cNode[0];
这个写的有点繁琐，不要放在这一起，你单独推一个，我再来改

2019-12-08 07:08 UTC, ADANIE commented on analysis/list.h
> +        node *case_list = nowNode->cNode[1]->cNode[0];
单独把switch这部push到一个新分支？

2019-12-08 13:37 UTC, Plane-walker requested changes

2019-12-08 13:37 UTC, Plane-walker commented on analysis/list.h
> +            control_jump->jump_false(label);
为假应该直接跳出循环

2019-12-08 14:02 UTC, ADANIE commented on analysis/list.h
> +            control_jump->jump_false(label);
OK 另外我顺便把for语句也写了吧？

2019-12-09 00:34 UTC, Plane-walker commented on analysis/list.h
> +            control_jump->jump_false(label);
你先弄指针

2019-12-09 00:40 UTC, Plane-walker approved these changes

2019-12-09 00:40 UTC, merged